name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: publish-nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.*

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: SpringHgui/publish-nuget@1.0.1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Serilog.Sinks.Kafka/Serilog.Sinks.Kafka.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
